### ISSUE TITLE
DST Support

### ISSUE THREAD

**Issue by rtscts** [kghrlabo/WordClockSingleLEDStrip#1]
Need DST support for Switzerland, don't now how to do ...

"CET-1CEST,M3.5.0,M10.5.0/3"

**Comment by kghrlabo** [comment]
The time in Switzerland is UTC (GMT) + 1 hour in winter and UTC + 2 hours in summer.
You can select "(GMT+01:00)"  in winter.

**Comment by rtscts** [comment]
Should be automatic ...
[https://randomnerdtutorials.com/esp32-ntp-timezones-daylight-saving/](url)
Many Tks

**Comment by kghrlabo** [comment]
Thank you for the useful information. My country does not have daylight saving time, and I have no plans to implement it. You are welcome to extend it yourself using the sample code. This issue is closed.
